services:
  mysql-user-service:
    image: 'mysql:8.0'
    container_name: 'mysql_user_service'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: user_service
      MYSQL_USER: nutrifituser
      MYSQL_PASSWORD: nutripass
    volumes:
        - 'mysql_data:/var/lib/mysql'
        - './docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
      - nutrifit-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5


  user-account-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-account-service:latest
    container_name: user_account_service
    ports:
      - '4000:4000'
      - '9000:9000'
    depends_on:
      mysql-user-service:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-user-service:3306/user_service
      SPRING_DATASOURCE_USERNAME: nutrifituser
      SPRING_DATASOURCE_PASSWORD: nutripass
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SERVER_PORT: 4000
      GRPC_PORT: 9000
    networks:
        - nutrifit-network
volumes:
  mysql_data:
networks:
  nutrifit-network:
    external: true
