services:
  mysql:
    image: 'mysql:8.0'
    container_name: 'mysql_user_service'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: user_service
      MYSQL_USER: nutrifituser
      MYSQL_PASSWORD: nutripass
    volumes:
        - 'mysql_data:/var/lib/mysql'
        - './docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql'
volumes:
  mysql_data:
