server:
  port: 4000
grpc:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_service?useSSL=false&allowPublicKeyRetrieval=true
    username: nutrifituser
    password: nutripass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
