name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI Checks and JaCoCo Coverage Report
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: nutrifit
          MYSQL_USER: nutrifituser
          MYSQL_PASSWORD: nutripass
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name : Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Wait for MySQL Service
        run: |
          echo "Waiting for MySQL..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u root -prootpass --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting..."
            sleep 2
          done

      - name: Build and Test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_service
          SPRING_DATASOURCE_USERNAME: nutrifituser
          SPRING_DATASOURCE_PASSWORD: nutripass
          SPRING_JPA_HIBERNATE_DDL_AUTO: none
        run: |
          mvn clean verify

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco
